on:
  pull_request:
     types:
     - closed

jobs:
  cancel:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    if: ${{ github.event.pull_request.merged != true }}
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const workflowIds = [
              '.github/workflows/cancel-test.yaml',
            ];

            for (const workflowId of workflowIds) {
              const workflowRuns = await github.rest.actions.listWorkflowRuns({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: workflowId,
                per_page: 100,
                event: 'pull_request',
                branch: context.payload.pull_request.head.ref,
              });

              const activeRuns = workflowRuns.data.workflow_runs.filter((workflowRun) => {
                return workflowRun.status === 'queued' || workflowRun.status === 'in_progress';
              });

              console.log(`pull reqがcloseされたので以下のjobをcancelします ${context.payload.pull_request.head.ref} ${workflowId}`);

              for (const activeRun of activeRuns) {
                await github.rest.actions.cancelWorkflowRun({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  run_id: activeRun.id,
                });
              }

              console.log(context.payload.pull_request);
              console.log(context.payload.pull_request.html_url);
            }
