on:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - uses: Ardiannn08/resolve-outdated-comment@3b3cf4b2651a84fac2d6a94c2aeca9ac7c05ac5f # v1.3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        filter-user: "github-actions"
    - uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: latest
    - env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: cat warnings.json | reviewdog -reporter=github-pr-review -f=rdjson
