name: check conflict
on:
  push:
  # schedule:
  # - cron: '0 5 * * 1-5'
jobs:
  check-conflict:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/github-script@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const script = require(`${process.env.GITHUB_WORKSPACE}/.github/conflict.js`)
          console.log(script({github, context}))
