on:
  pull_request:
    types:
    - opend
    - synchronize
    - reopened
    - ready_for_review

jobs:
  test:
    if: ${{ ! github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - run: echo hello
    - run: echo '${{ toJSON(github) }}'
