name: aaa
on:
  workflow_dispatch:
    inputs:
      base_branch:
        required: false
        default: 'main'
      head_branch:
        required: false
        default: 'test-1'
      pull_req_title:
        required: false
        default: 'リリース'        
jobs:
  release-pull-req:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - uses: actions/github-script@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.pulls.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            head: "${{ github.event.inputs.head_branch }}",
            base: "${{ github.event.inputs.base_branch }}",
            title: "${{ github.event.inputs.pull_req_title }}"
          });
