name: delete pull request comments
on:
  pull_request:
    types: [synchronize, reopened, edited]
jobs:
  delete-bot-comments:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
    - uses: actions/github-script@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const script = require(`${process.env.GITHUB_WORKSPACE}/.github/delete-bot-comments.js`)
          console.log(script({github, context}))
