on:
  pull_request:

jobs:
  ready-for-review:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          console.log(context);
          console.log(github);
          console.log(context.pull_request.node_id);
          console.log(github.event.pull_request.node_id);
          const query = `
            mutation($id: ID!) {
              markPullRequestReadyForReview(input: { pullRequestId: $id }) {
                pullRequest {
                  id
                }
              }
            }
          `;
          const variables = {
            id: github.event.pull_request.node_id
          }
          const result = await github.graphql(query, variables)
          console.log(result)
