on:
  issue_comment:
    types: [created]
permissions: write-all
jobs:
  rebase:
    timeout-minutes: 5
    if: github.event.issue.pull_request != '' && github.event.comment.body == '/rebase'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791 # v2
      with:
        fetch-depth: 0
    - env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - uses: actions/github-script@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const script = require(`${process.env.GITHUB_WORKSPACE}/.github/check-rebase-branch.js`)
          console.log(script({github, context}))
    - uses: cirrus-actions/rebase@7e3fc92f1b6a4d19f607d5cb3d70ce8a1ec13b1c
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
