on:
  issue_comment:
    types: [created]
jobs:
  rebase:
    timeout-minutes: 5
    if: github.event.issue.pull_request != '' && github.event.comment.body == '/rebase'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - uses: cirrus-actions/rebase@7e3fc92f1b6a4d19f607d5cb3d70ce8a1ec13b1c
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
