on:
  pull_request:
  
  
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - if: github.event.action == 'synchronize' || github.event.action == 'reopened'
      run: echo '${{ toJSON(github) }}'
