on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - run: echo '${{ toJSON(github) }}'
    - uses: peter-evans/enable-pull-request-automerge@60812ab1c2c6c6a8932b4d6e059becafaf386256 # v2.3.0
