on:
  push:

jobs:
  test1:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
    - run: |
        wget https://repo1.maven.org/maven2/org/scala-lang/scala3-compiler_3/maven-metadata.xml
        xmllint --xpath "/metadata/versioning/latest/text()" maven-metadata.xml
