on:
  pull_request:

jobs:
  test1:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    if: ${{ !startsWith(github.context.payload.pull_request.title, '[2.x]') && (github.context.payload.pull_request.base.ref == 'main') }}
    steps:
    - uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          await github.rest.pulls.update({
            owner: github.context.repo.owner,
            repo: github.context.repo.repo,
            pull_number: github.context.payload.pull_request.number,
            title: `[2.x] ${github.context.payload.pull_request.title}`
          });
          
