on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    # - run: echo '${{ toJSON(github) }}'
    - uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const p = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: 17
          });
          console.log(p);
