on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - if: github.event.actions == 'synchronize' || github.event.actions == 'reopened'
      run: echo '${{ toJSON(github) }}'
