on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@1df8dbefe2a8cbc99770194893dd902763bee34b # v3.9.0
      with:
        java-version: 11
        distribution: adopt
    - run: sbt scalafmtAll scalafmtSbt
    - name: Check diff
      run: git diff --exit-code
    - uses: reviewdog/action-suggester@v1.6.0
      if: failure()
      with:
        tool_name: scalafmt
