on:
  pull_request:
  push:
    branches:
    - main

jobs:
  test1:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
    - run: echo 1
  test2:
    needs: test1
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
    - run: echo 2
  test3:
    needs: test2
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
    - run: echo 3
